		index index.php;

		location ^~ /private/ {
				return 404;
		}

		location = /location-release.apk {
				add_header Cache-Control "no-store";
				try_files /location-release.apk =404;
		}

		location / {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				try_files $uri $uri/ /index.php?$query_string;
		}

		location /api/ {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				try_files $uri =404;
		}
