		index index.php;

		location ^~ /private/ {
				return 404;
		}

		location = /location-release.apk {
				add_header Cache-Control "no-store";
				try_files /location-release.apk =404;
		}

		location = /_AMapService/v4/map/styles {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				set $args "$args&jscode=你的高德安全密钥";
				proxy_ssl_server_name on;
				proxy_set_header Host webapi.amap.com;
				proxy_pass https://webapi.amap.com/v4/map/styles;
		}

		location = /_AMapService/v3/vectormap {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				set $args "$args&jscode=你的高德安全密钥";
				proxy_ssl_server_name on;
				proxy_set_header Host fmap01.amap.com;
				proxy_pass https://fmap01.amap.com/v3/vectormap;
		}

		location ^~ /_AMapService/ {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				set $args "$args&jscode=你的高德安全密钥";
				proxy_ssl_server_name on;
				proxy_set_header Host restapi.amap.com;
				proxy_pass https://restapi.amap.com/;
		}

		location / {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				try_files $uri $uri/ /index.php?$query_string;
		}

		location /api/ {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				try_files $uri =404;
		}
